export const content = {
  tr: {
    loading:"Yükleniyor...",
    welcome: "Hoş Geldiniz",
    signIn: "Giriş Yap",
    signUp: "Kayıt Ol",
    signUpDescription: "E-posta ile kayıt olun veya Google ile devam edin.",
    signInDescription: "E-posta ile giriş yapın veya Google ile devam edin.",
    fullName: "İsim Soyisim",
    email: "E-posta",
    password: "Şifre",
    passwordConfirm: "Şifre Tekrar",
    passwordsDoNotMatch: "Şifreler eşleşmiyor.",
    registrationError: "Kayıt hatası",
    alreadyHaveAccount: "Zaten bir hesabın var mı?",
    forgotPassword: "Şifreni mi unuttun?",
    sendResetLink: "Sıfırlama linki gönder",
    changepassword: "Şifre Değiştirme",
    again: "Tekrar",
    change:"Değiştir",
    resetPassword: "Şifre Sıfırlama",
    resetPasswordInstructions: "E-posta adresini gir, sana bir sıfırlama bağlantısı gönderelim.",
    newPassword: "Yeni Şifre",
    newPasswordConfirm: "Yeni Şifre Tekrar",
    updatePassword: "Şifreyi Güncelle",
    passwordResetSuccess: "Şifre başarıyla güncellendi. Giriş sayfasına yönlendiriliyorsunuz...",
    passwordResetError: "Şifre güncellenemedi",
     passwordResetLinkSent: "Şifre sıfırlama bağlantısı e-posta adresine gönderildi.",
resetPasswordDesc: "E-posta adresini gir, sana bir sıfırlama bağlantısı gönderelim.",
    verifyEmailTitle: "📩 E-posta Doğrulama",
    verifyEmailInstruction: "Kayıt işlemini tamamlamak için e-posta adresine gönderilen bağlantıya tıkla.",
    verifyEmailNote: "Doğrulama bağlantısına tıkladıktan sonra giriş yapabilirsin.",
    signInWithGoogle: "Google ile giriş yap",
    signInWithFacebook: "Facebook ile giriş yap",
    loginFailed: "Giriş başarısız",
    registrationSuccess: "Kayıt başarılı",
    loadingRedirectMessage: "Giriş tamamlanıyor, lütfen bekleyin...",
    noAccount: "Hesabın yok mu?",
    portfolioValue: "Portföy Değeri",
    manageFinancialFuture: "Finansal Geleceğinizi Yönetin",
    trackInvestments: "PortfoyPro ile yatırımlarınızı takip edin, analiz edin ve finansal hedeflerinize ulaşın.",
    portfolioSummary: "Portföy Özeti",
    assetDistribution: "Varlık Dağılımı",
    recentTransactions: "Son İşlemler",
    transactions:"İşlemler",
    asset: "Varlık",
    transaction: "İşlem",
    amount: "Miktar",
    date: "Tarih",
    whyPortfoyPro: "Neden PortfoyPro?",
    realTimeTracking: "Gerçek Zamanlı Takip",
    realTimeTrackingDesc: "Tüm yatırımlarınızı tek bir platformda gerçek zamanlı olarak takip edin. Hisse senetleri, kripto paralar, fonlar ve daha fazlası.",
    smartPortfolioAnalysis: "Akıllı Portföy Analizi",
    smartPortfolioAnalysisDesc: "Gelişmiş analiz araçlarıyla portföyünüzün performansını değerlendirin, risk analizini görün ve daha bilinçli yatırım kararları alın.",
    secureAndPrivate: "Güvenli ve Özel",
    secureAndPrivateDesc: "Verileriniz en yüksek güvenlik standartlarıyla korunur. Hesap bilgileriniz ve finansal verileriniz her zaman güvende kalır.",
    shapeFinancialFuture: "Finansal Geleceğinizi Bugün Şekillendirin",
    startManagingInvestments: "PortfoyPro ile yatırımlarınızı yönetmeye hemen başlayın ve finansal hedeflerinize daha hızlı ulaşın.",
    startFree: "Hemen Ücretsiz Başlayın",
    quickLinks: "Hızlı Bağlantılar",
    resources: "Kaynaklar",
    legal: "Yasal",
    about: "Hakkımızda",
    buy: "Alış",
    sell: "Satış",
    stocks: "Hisse Senetleri",
    crypto: "Kripto",
    bonds: "Tahvil/Bono",
    gold: "Altın",
    cash: "Nakit",
    features: "Özellikler",
    pricing: "Fiyatlandırma",
    contact: "İletişim",
    blog: "Blog",
    logout:"Çıkış Yap",
    guides: "Rehberler",
    faq: "SSS",
    support: "Destek",
    privacyPolicy: "Gizlilik Politikası",
    termsOfUse: "Kullanım Şartları",
    cookiePolicy: "Çerez Politikası",
    kvkk: "KVKK",
    disclaimer: "Yasal Uyarılar",
    footerText: "2024 PortfoyPro. Tüm hakları saklıdır.",
    footer: {
      contact: {
        title: "İletişim",
        emailLabel: "E-posta",
        phoneLabel: "Telefon",
        addressLabel: "Adres",
        hoursLabel: "Çalışma Saatleri",
        hours: "Hafta içi her gün 09:00 - 18:00",
      },
      cookiePolicy: {
        title: "Çerez Politikası",
        p1: "Web sitemiz çerezleri, kullanıcı deneyimini geliştirmek ve analiz hizmetleri sunmak amacıyla kullanır.",
        p2: "Çerezler, tarayıcınız tarafından cihazınıza kaydedilen küçük metin dosyalarıdır. Bu dosyalar site tercihlerinizin hatırlanmasına yardımcı olur.",
        p3: "Çerezleri reddetmek isterseniz, tarayıcı ayarlarınızdan bu tercihleri değiştirebilirsiniz. Ancak bazı özellikler etkilenebilir.",
      },
      faq: {
        title: "Sıkça Sorulan Sorular",
        items: [
          {
            q: "PortföyPro nedir?",
            a: "PortföyPro, yatırımlarınızı tek bir yerden takip edebileceğiniz kapsamlı bir portföy yönetim aracıdır.",
          },
          {
            q: "Hesabımı nasıl silebilirim?",
            a: "Ayarlar sayfasından hesabınızı silme isteği oluşturabilirsiniz.",
          },
          {
            q: "Verilerim güvende mi?",
            a: "Evet. Tüm verileriniz şifreli olarak saklanmakta ve üçüncü taraflarla paylaşılmamaktadır.",
          },
        ],
      },
     
        gdpr: {
          title: "Veri Koruma (GDPR)",
          p1: "PortföyPro olarak kullanıcı gizliliğine önem veriyoruz. Verileriniz yalnızca hizmet sunmak amacıyla toplanır ve işlenir.",
          p2: "Verilerinizi görüntüleme, düzeltme, silme veya işlenmesine itiraz etme hakkına sahipsiniz.",
          p3: "Bu hakları kullanmak için bizimle iletişime geçebilirsiniz: info@portfoypro.com",
      },
      guides: {
        title: "Kullanım Rehberleri",
        items: [
          "1. Yeni bir portföy oluşturmak için 'Portföylerim' sekmesine gidin.",
          "2. Varlık eklemek için oluşturduğunuz portföyü seçin ve 'Varlık Ekle' butonuna tıklayın.",
          "3. Alım-satım işlemleri için 'İşlemler' menüsünden ilgili varlığı seçin.",
          "4. Grafiklerle performans takibi için 'Dashboard' sayfasını kullanın.",
          "5. Ayarlar bölümünden tema ve dil tercihinizi düzenleyebilirsiniz.",
        ],
      },
      privacyPolicy: {
        title: "Gizlilik Politikası",
        p1: "Kullanıcı bilgileriniz gizli tutulur ve yasal zorunluluklar dışında üçüncü taraflarla paylaşılmaz.",
        p2: "Veriler yalnızca kullanıcı deneyimini geliştirmek, güvenliği sağlamak ve hizmet sunmak amacıyla işlenir.",
        p3: "Detaylı gizlilik politikamız için bizimle iletişime geçebilirsiniz: info@portfoypro.com",
      },

       termsOfUse: {
    title: "Kullanım Koşulları",
    p1: "PortföyPro'yu kullanan tüm kullanıcılar, belirtilen kuralları ve politikaları kabul etmiş sayılır.",
    p2: "Hizmetlerimizde yapılan değişiklikler önceden haber verilmeksizin uygulanabilir.",
    p3: "Kullanıcılar, PortföyPro'yu yalnızca yasal amaçlarla kullanmayı taahhüt eder.",
      },
      
      
 

    },
    
   
        home:"Anasayfa",
     
    myPortfolio: "Portföylerim",
    portfolioAdd: "Portföy Ekle",
    editPortfolio: "Portföyü Düzenle",
    newPortfolio: "Yeni Portfoy",
    
    deletePortfolio: "Portföyü silmek istiyor musun?",
    deletePortfolioDescription: "Bu işlem geri alınamaz. portföyü kalıcı olarak silinecek.",
    deleteAsset: "Varlığı silmek istiyor musun?",
    deleteAssetDescription: "Bu işlem geri alınamaz. Bu varlık portföyden kaldırılacak.",
    cancel: "İptal",
    yesDelete:"Evet ,Sil",
    noPortfolio: "Portfolyo Bulunamadi.",
    selectPortfolio:"Portföy Seçin",
        selectPortfolioNo: "Seçili portföyde varlık yok",
         noAsset:"varlık yok",
         addAsset:"Varlık Ekle",
    assets: "Varliklar",
    selectAsset:"Varlik Seç",
    wantToAdd: "Eklemek istediğiniz varlıkları seçin",
    addSelectedAssets:"Seçilen Varlıkları Ekle",
    thereNoAssets:"Bu portföyde henüz varlık yok.",
    editAsset:"Varlik Düzenle",
    save: "Kaydet",
    name: "Ad",
    description: "Aciklama",
    transactionAdd: "İşlem Ekle",
    transactionType:"İşlem Tipi",
    unitPrice: "Birim Fiyat",
    currency: "Para Birimi",
    rate: "Kur",
    transactionDate: "İşlem Tarihi",
    transactionFee: "İşlem Ücreti",
    themeSelection: "Tema Seçimi",
    light: "Açık",
    dark: "Koyu",
    system: "Sistem",
    languageSelection:"Dil Seçimi",
    profile: "Profil",
    settings: "Ayarlar",





  },
  en: {
    loading:"Loading...",
     
       home:"Home",
      
    myPortfolio: "My Portfolios",
    portfolioAdd: "Add Portfolio",
    editPortfolio: "Edit Portfolio",
    newPortfolio:"New Portfolio",
    deletePortfolio: "Do you want to delete the portfolio?",
    deletePortfolioDescription: "This action cannot be reversed. Portfolio will be permanently deleted.",
    deleteAsset: "Do you want to delete the asset?",
    deleteAssetDescription: "This action cannot be reversed. Asset will be permanently deleted.",

    cancel: "Cancel",
    yesDelete:"Yes, Delete",
    noPortfolio: "Portfolio Not Found",
    selectPortfolio:"Select Portfolio",
        selectPortfolioNo: "There are no assets in the selected portfolio",
    noAsset: "there is no asset",
    addAsset: "Add Asset",
    assets: "Assets",
  selectAsset:"Select Asset",
    wantToAdd: "Select the assets you want to add",
    addSelectedAssets: "Add Selected Assets",
    thereNoAssets: "There are no assets in this portfolio yet.",
     editAsset:"Edit Asset",
 save:"Save",
    name: "Name",
    description: "Description",
    transactionAdd: "Transaction Add",
    transactionType: "Transaction Type",
    unitPrice: "Unit Price",
    currency: "Currency",
    rate: "Rate",
    transactionDate: "Transaction Date",
    transactionFee:"Transaction Fee",
    themeSelection: "Theme Selection",
    light: "Light",
    dark: "Dark",
    system: "System",
    languageSelection: "Language Selection",
    profile:"Profile",
settings:"Settings",


    welcome: "Welcome",
    signIn: "Sign In",
    signUp: "Sign Up",
    signUpDescription: "Sign up with email or continue with Google.",
    signInDescription: "Sign in with email or continue with Google.",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    passwordConfirm: "Confirm Password",
    passwordsDoNotMatch: "Passwords do not match.",
    registrationError: "Registration error",
    alreadyHaveAccount: "Already have an account?",
    forgotPassword: "Forgot your password?",
    sendResetLink: "Send Reset Link",
    changepassword: "Change Password",
    change:"Change",
    again:"Again",
    resetPassword: "Password Reset",
    resetPasswordInstructions: "Enter your email, we will send you a reset link.",
    newPassword: "New Password",
    newPasswordConfirm: "Confirm New Password",
    updatePassword: "Update Password",
    passwordResetSuccess: "Password updated successfully. Redirecting to login...",
    passwordResetError: "Password could not be updated",
    verifyEmailTitle: "📩 Email Verification",
    passwordResetLinkSent: "Password reset link has been sent to your email address.",
resetPasswordDesc: "Enter your email address, and we will send you a reset link.",

    verifyEmailInstruction: "To complete your registration, click the link sent to your email address.",
    verifyEmailNote: "You can log in after clicking the verification link.",
    signInWithGoogle: "Sign in with Google",
    signInWithFacebook: "Sign in with Facebook",
    loginFailed: "Login failed",
    registrationSuccess: "Registration successful",
    loadingRedirectMessage: "Completing login, please wait...",
    noAccount: "Don't have an account?",
    portfolioValue: "Portfolio Value",
    manageFinancialFuture: "Manage Your Financial Future",
    trackInvestments: "Track, analyze, and achieve your financial goals with PortfoyPro.",
    portfolioSummary: "Portfolio Summary",
    assetDistribution: "Asset Distribution",
    recentTransactions: "Recent Transactions",
    transactions:"Transactions",
    asset: "Asset",
    transaction: "Transaction",
    amount: "Amount",
    date: "Date",
    whyPortfoyPro: "Why PortfoyPro?",
    realTimeTracking: "Real-Time Tracking",
    realTimeTrackingDesc: "Track all your investments in real-time on a single platform. Stocks, cryptocurrencies, funds, and more.",
    smartPortfolioAnalysis: "Smart Portfolio Analysis",
    smartPortfolioAnalysisDesc: "Evaluate your portfolio's performance with advanced analysis tools, see risk analysis, and make more informed investment decisions.",
    secureAndPrivate: "Secure and Private",
    secureAndPrivateDesc: "Your data is protected with the highest security standards. Your account information and financial data are always safe.",
    shapeFinancialFuture: "Shape Your Financial Future Today",
    startManagingInvestments: "Start managing your investments with PortfoyPro today and reach your financial goals faster.",
    startFree: "Start Free Now",
    quickLinks: "Quick Links",
    resources: "Resources",
    legal: "Legal",
    about: "About",
    buy: "Buy",
    sell: "Sell",
    stocks: "Stocks",
    crypto: "Crypto",
    bonds: "Bonds",
    gold: "Gold",
    cash: "Cash",
    features: "Features",
    pricing: "Pricing",
    contact: "Contact",
    blog: "Blog",
    logout:"Log Out",
    guides: "Guides",
    faq: "FAQ",
    support: "Support",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    cookiePolicy: "Cookie Policy",
    kvkk: "GDPR",
    disclaimer: "Disclaimer",
    footerText: "2024 PortfoyPro. All rights reserved.",
    footer: {
      contact: {
        title: "Contact",
        emailLabel: "Email",
        phoneLabel: "Phone",
        addressLabel: "Address",
        hoursLabel: "Working Hours",
        hours: "Weekdays 9:00 AM - 6:00 PM",
      },
      cookiePolicy: {
        title: "Cookie Policy",
        p1: "Our website uses cookies to improve user experience and provide analytical services.",
        p2: "Cookies are small text files stored on your device by your browser, helping to remember site preferences.",
        p3: "If you wish to disable cookies, you can do so through your browser settings. Some features may be affected.",
      },
      faq: {
        title: "Frequently Asked Questions",
        items: [
          {
            q: "What is PortföyPro?",
            a: "PortföyPro is a comprehensive portfolio tracking tool to manage all your investments in one place.",
          },
          {
            q: "How can I delete my account?",
            a: "You can request account deletion from the settings page.",
          },
          {
            q: "Is my data secure?",
            a: "Yes. All your data is stored securely and never shared with third parties.",
          },
        ],
      },
      gdpr: {
        title: "Data Protection (GDPR)",
        p1: "At PortföyPro, we value your privacy. Your data is collected and processed solely to provide our services.",
        p2: "You have the right to access, correct, delete, or object to the processing of your personal data.",
        p3: "To exercise these rights, please contact us at: info@portfoypro.com",
      },
      guides: {
        title: "User Guides",
        items: [
          "1. To create a new portfolio, go to the 'My Portfolios' section.",
          "2. To add an asset, select your portfolio and click 'Add Asset'.",
          "3. For buy/sell operations, use the 'Transactions' menu.",
          "4. Use the 'Dashboard' page to track your portfolio's performance.",
          "5. You can change theme and language from the Settings section.",
        ],
      },
      privacyPolicy: {
        title: "Privacy Policy",
        p1: "Your information is kept confidential and is not shared with third parties unless legally required.",
        p2: "Data is processed only to enhance user experience, ensure security, and deliver services.",
        p3: "For a detailed privacy policy, feel free to contact us at: info@portfoypro.com",
      },
      termsOfUse: {
        title: "Terms of Use",
        p1: "By using PortföyPro, all users agree to comply with the stated rules and policies.",
        p2: "Changes to our services may be applied without prior notice.",
        p3: "Users agree to use PortföyPro only for lawful purposes.",
      }
    }
    
  },
} as const;
